#!/bin/bash

if [ -d modules ]
  then 
   rm -r modules
   mkdir modules
 fi

cp fs/cifs/*.ko ./modules
cp net/sched/cls_flow.ko ./modules
cp net/sched/sch_dsmark.ko ./modules
cp arch/arm/common/cpaccess.ko ./modules
cp arch/arm/mach-msm/dma_test.ko ./modules
cp arch/arm/mach-msm/reset_modem.ko ./modules
cp arch/arm/mach-msm/dal_remotetest.ko ./modules
cp arch/arm/oprofile/oprofile.ko ./modules
cp drivers/mtd/tests/mtd_readtest.ko ./modules
cp drivers/mtd/tests/mtd_stresstest.ko ./modules
cp drivers/mtd/tests/mtd_erasepart.ko ./modules
cp drivers/mtd/tests/mtd_speedtest.ko ./modules
cp drivers/mtd/tests/mtd_oobtest.ko ./modules
cp drivers/mtd/tests/mtd_subpagetest.ko ./modules
cp drivers/mtd/tests/mtd_nandecctest.ko ./modules
cp drivers/mtd/tests/mtd_torturetest.ko ./modules
cp drivers/mtd/tests/mtd_pagetest.ko ./modules
cp drivers/net/wireless/bcm4329/dhd.ko ./modules
cp drivers/input/evbug.ko ./modules
cp drivers/media/video/gspca/gspca_main.ko ./modules
cp drivers/bluetooth/bthid/bthid.ko ./modules
cp drivers/param/sec_param.ko ./modules
cp drivers/crypto/msm/qce.ko ./modules
cp drivers/crypto/msm/qcedev.ko ./modules
cp drivers/crypto/msm/qcrypto.ko ./modules
cp drivers/scsi/scsi_wait_scan.ko ./modules
cp crypto/ansi_cprng.ko ./modules
